[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npx drizzle-kit push --force"]

[start]
cmd = "NODE_ENV=production node dist/index.cjs"
