export const BLOG_301S: Record<string, string> = {};

export const BLOG_410S = new Set<string>([
  "/blog/weekly-digestive-health-tips",
  "/blog/weekly-digestive-health-tips-dietary-fiber",
  "/blog/weekly-digestive-health-tips-stress",
  "/blog/weekly-digestive-health-tips-2",
  "/blog/weekly-digestive-health-tips-3",
  "/blog/weekly-digestive-health-tips-4",
  "/blog/weekly-digestive-health-tips-5",
  "/blog/weekly-digestive-health-blog-hydration",
  "/blog/weekly-digestive-health-tips-probiotics",
  "/blog/weekly-product-spotlight",
  "/blog/go-green",
  "/blog/fish-in-a-bowl",
  "/blog/tea-time",
  "/blog/get-out-more",
  "/blog/what-tea-is-right-for-me",
  "/blog/tea-for-brain-health",
  "/blog/nausea-wristband-uses-acupuncture-point",
  "/blog/still-point-inducer",
  "/blog/what-is-in-your-fish-oil",
  "/blog/arsenic-in-rice",
  "/blog/caught-a-cold",
  "/blog/most-important-supplement-fact",
  "/blog/cold-and-flu-season",
  "/blog/health-habit-success",
  "/blog/is-fish-oil-alone-enough",
  "/blog/got-rocks",
]);
